import { Category, Brand, Product, Review, FAQ, ProductDocument, PriceHistoryPoint, Order, User } from '../src/types';

export const initialCategories: Category[] = [
  {
    id: 'cat-laptops',
    name: 'Laptops & Computers',
    slug: 'laptops-computers',
    parentId: null,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80',
    description: 'High-performance laptops, ultrabooks, and desktop workstations',
    productCount: 4,
  },
  {
    id: 'cat-phones',
    name: 'Smartphones & Tablets',
    slug: 'smartphones-tablets',
    parentId: null,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    description: 'Flagship 5G smartphones, foldables, and pro tablets',
    productCount: 4,
  },
  {
    id: 'cat-audio',
    name: 'Audio & Headphones',
    slug: 'audio-headphones',
    parentId: null,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    description: 'Studio monitors, noise-canceling headphones, and wireless earbuds',
    productCount: 3,
  },
  {
    id: 'cat-displays',
    name: 'Monitors & Displays',
    slug: 'monitors-displays',
    parentId: null,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
    description: 'UltraWide OLED gaming displays and color-accurate 4K monitors',
    productCount: 3,
  },
  {
    id: 'cat-gaming',
    name: 'Gaming & Gear',
    slug: 'gaming-gear',
    parentId: null,
    imageUrl: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&auto=format&fit=crop&q=80',
    description: 'Next-gen consoles, graphics cards, and mechanical peripherals',
    productCount: 3,
  },
  {
    id: 'cat-smarthome',
    name: 'Wearables & Smart Home',
    slug: 'wearables-smart-home',
    parentId: null,
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
    description: 'Smartwatches, fitness rings, security hubs, and smart IoT',
    productCount: 2,
  },
];

export const initialBrands: Brand[] = [
  {
    id: 'brand-apple',
    name: 'Apple',
    slug: 'apple',
    logoUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=120&auto=format&fit=crop&q=80',
    description: 'Pioneering premium hardware, Apple Silicon chips, and unified ecosystem devices.',
    website: 'https://apple.com',
  },
  {
    id: 'brand-samsung',
    name: 'Samsung',
    slug: 'samsung',
    logoUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=120&auto=format&fit=crop&q=80',
    description: 'Global leader in Dynamic AMOLED displays, Galaxy processors, and consumer electronics.',
    website: 'https://samsung.com',
  },
  {
    id: 'brand-sony',
    name: 'Sony',
    slug: 'sony',
    logoUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=120&auto=format&fit=crop&q=80',
    description: 'Legendary audio fidelity, PlayStation gaming architectures, and camera sensors.',
    website: 'https://sony.com',
  },
  {
    id: 'brand-dell',
    name: 'Dell Technologies',
    slug: 'dell',
    logoUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=120&auto=format&fit=crop&q=80',
    description: 'Award-winning XPS InfinityEdge laptops and UltraSharp professional monitors.',
    website: 'https://dell.com',
  },
  {
    id: 'brand-asus',
    name: 'ASUS ROG',
    slug: 'asus-rog',
    logoUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=120&auto=format&fit=crop&q=80',
    description: 'Republic of Gamers engineered extreme cooling, high refresh rates, and gaming rigs.',
    website: 'https://rog.asus.com',
  },
  {
    id: 'brand-nvidia',
    name: 'NVIDIA',
    slug: 'nvidia',
    logoUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=120&auto=format&fit=crop&q=80',
    description: 'World pioneer in GPU accelerated computing, DLSS AI graphics, and Ray Tracing.',
    website: 'https://nvidia.com',
  },
  {
    id: 'brand-bose',
    name: 'Bose',
    slug: 'bose',
    logoUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=120&auto=format&fit=crop&q=80',
    description: 'Acoustic research pioneers known for world-class active noise cancellation.',
    website: 'https://bose.com',
  },
  {
    id: 'brand-logitech',
    name: 'Logitech G',
    slug: 'logitech-g',
    logoUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=120&auto=format&fit=crop&q=80',
    description: 'Mastery in LIGHTSPEED wireless peripherals, mechanical switches, and esports gear.',
    website: 'https://logitechg.com',
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Alex Vance (Admin)',
    email: 'admin@voltmart.io',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'usr-customer-1',
    name: 'David Chen',
    email: 'david.chen@example.com',
    role: 'CUSTOMER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-02-10T14:30:00Z',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-macbook-pro-16',
    name: 'MacBook Pro 16" (M3 Max, 64GB Unified RAM, 1TB SSD)',
    sku: 'APP-MBP16-M3MAX',
    barcode: '190199438210',
    categoryId: 'cat-laptops',
    brandId: 'brand-apple',
    description: 'Supercharged by Apple M3 Max with a 16-core CPU and 40-core GPU. Features an extraordinary Liquid Retina XDR 120Hz ProMotion display, studio-grade 6-speaker sound system, and up to 22 hours of battery life.',
    basePrice: 3499.00,
    salePrice: 3299.00,
    stockQuantity: 18,
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isDeal: true,
    images: [
      { id: 'img-mbp-1', productId: 'prod-macbook-pro-16', imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'MacBook Pro 16 in Space Black' },
      { id: 'img-mbp-2', productId: 'prod-macbook-pro-16', imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80', isPrimary: false, altText: 'Liquid Retina XDR Display View' },
      { id: 'img-mbp-3', productId: 'prod-macbook-pro-16', imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80', isPrimary: false, altText: 'Magic Keyboard and Force Touch Trackpad' },
    ],
    specifications: [
      { id: 'sp-1', productId: 'prod-macbook-pro-16', specGroup: 'Display', specName: 'Screen Size', specValue: '16.2-inch' },
      { id: 'sp-2', productId: 'prod-macbook-pro-16', specGroup: 'Display', specName: 'Resolution', specValue: '3456 x 2234 (Liquid Retina XDR)' },
      { id: 'sp-3', productId: 'prod-macbook-pro-16', specGroup: 'Display', specName: 'Refresh Rate', specValue: '120Hz ProMotion' },
      { id: 'sp-4', productId: 'prod-macbook-pro-16', specGroup: 'Performance', specName: 'Processor', specValue: 'Apple M3 Max (16-core CPU)' },
      { id: 'sp-5', productId: 'prod-macbook-pro-16', specGroup: 'Performance', specName: 'GPU', specValue: '40-core GPU with Hardware Ray Tracing' },
      { id: 'sp-6', productId: 'prod-macbook-pro-16', specGroup: 'Memory & Storage', specName: 'RAM', specValue: '64GB Unified Memory' },
      { id: 'sp-7', productId: 'prod-macbook-pro-16', specGroup: 'Memory & Storage', specName: 'Storage', specValue: '1TB NVMe SSD' },
      { id: 'sp-8', productId: 'prod-macbook-pro-16', specGroup: 'Battery & Power', specName: 'Battery Capacity', specValue: '100Wh (Up to 22 hrs)' },
      { id: 'sp-9', productId: 'prod-macbook-pro-16', specGroup: 'Connectivity', specName: 'Ports', specValue: '3x Thunderbolt 4 / USB-C, HDMI 2.1, SDXC, MagSafe 3' },
      { id: 'sp-10', productId: 'prod-macbook-pro-16', specGroup: 'Design & Build', specName: 'Weight', specValue: '2.16 kg (4.8 lbs)' },
    ],
    createdAt: '2025-01-10T12:00:00Z',
    updatedAt: '2025-03-01T15:00:00Z',
  },
  {
    id: 'prod-dell-xps-16',
    name: 'Dell XPS 16 9640 (Core Ultra 9, RTX 4070, 32GB RAM, 1TB)',
    sku: 'DEL-XPS16-9640',
    barcode: '884116449102',
    categoryId: 'cat-laptops',
    brandId: 'brand-dell',
    description: 'Crafted with CNC machined aluminum and Gorilla Glass 3. Powered by Intel Core Ultra 9 185H with integrated AI NPU and NVIDIA GeForce RTX 4070. Stunning 16.3" 4K+ OLED touch screen.',
    basePrice: 2899.00,
    salePrice: 2699.00,
    stockQuantity: 12,
    rating: 4.7,
    reviewCount: 29,
    isFeatured: true,
    images: [
      { id: 'img-xps-1', productId: 'prod-dell-xps-16', imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Dell XPS 16 Platinum' },
      { id: 'img-xps-2', productId: 'prod-dell-xps-16', imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80', isPrimary: false, altText: 'InfinityEdge OLED panel' },
    ],
    specifications: [
      { id: 'sp-11', productId: 'prod-dell-xps-16', specGroup: 'Display', specName: 'Screen Size', specValue: '16.3-inch' },
      { id: 'sp-12', productId: 'prod-dell-xps-16', specGroup: 'Display', specName: 'Resolution', specValue: '3840 x 2400 (4K+ OLED Touch)' },
      { id: 'sp-13', productId: 'prod-dell-xps-16', specGroup: 'Display', specName: 'Refresh Rate', specValue: '90Hz VRR' },
      { id: 'sp-14', productId: 'prod-dell-xps-16', specGroup: 'Performance', specName: 'Processor', specValue: 'Intel Core Ultra 9 185H (16 Cores, 5.1GHz)' },
      { id: 'sp-15', productId: 'prod-dell-xps-16', specGroup: 'Performance', specName: 'GPU', specValue: 'NVIDIA GeForce RTX 4070 (8GB GDDR6)' },
      { id: 'sp-16', productId: 'prod-dell-xps-16', specGroup: 'Memory & Storage', specName: 'RAM', specValue: '32GB LPDDR5x 7467MHz' },
      { id: 'sp-17', productId: 'prod-dell-xps-16', specGroup: 'Memory & Storage', specName: 'Storage', specValue: '1TB PCIe 4.0 NVMe SSD' },
      { id: 'sp-18', productId: 'prod-dell-xps-16', specGroup: 'Battery & Power', specName: 'Battery Capacity', specValue: '99.5Wh (130W USB-C Type-C)' },
      { id: 'sp-19', productId: 'prod-dell-xps-16', specGroup: 'Connectivity', specName: 'Ports', specValue: '3x Thunderbolt 4 / Type-C, microSDXC v6.0, 3.5mm jack' },
      { id: 'sp-20', productId: 'prod-dell-xps-16', specGroup: 'Design & Build', specName: 'Weight', specValue: '2.13 kg (4.7 lbs)' },
    ],
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2025-03-02T08:00:00Z',
  },
  {
    id: 'prod-rog-zephyrus-g16',
    name: 'ASUS ROG Zephyrus G16 (OLED 240Hz, RTX 4080, 32GB RAM)',
    sku: 'ASU-ROG-G16-4080',
    barcode: '197105234901',
    categoryId: 'cat-laptops',
    brandId: 'brand-asus',
    description: 'The ultra-sleek esports powerhouse. Features a 16" ROG Nebula Display 2.5K 240Hz 0.2ms OLED panel with G-SYNC, Slash Lighting on CNC aluminum lid, and vapor chamber liquid metal cooling.',
    basePrice: 2699.00,
    salePrice: 2499.00,
    stockQuantity: 8,
    rating: 4.8,
    reviewCount: 35,
    isFeatured: true,
    isDeal: true,
    images: [
      { id: 'img-rog-1', productId: 'prod-rog-zephyrus-g16', imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'ROG Zephyrus G16 Eclipse Gray' },
    ],
    specifications: [
      { id: 'sp-21', productId: 'prod-rog-zephyrus-g16', specGroup: 'Display', specName: 'Screen Size', specValue: '16.0-inch' },
      { id: 'sp-22', productId: 'prod-rog-zephyrus-g16', specGroup: 'Display', specName: 'Resolution', specValue: '2560 x 1600 (2.5K Nebula OLED)' },
      { id: 'sp-23', productId: 'prod-rog-zephyrus-g16', specGroup: 'Display', specName: 'Refresh Rate', specValue: '240Hz / 0.2ms G-Sync' },
      { id: 'sp-24', productId: 'prod-rog-zephyrus-g16', specGroup: 'Performance', specName: 'Processor', specValue: 'Intel Core Ultra 9 185H (5.1GHz)' },
      { id: 'sp-25', productId: 'prod-rog-zephyrus-g16', specGroup: 'Performance', specName: 'GPU', specValue: 'NVIDIA GeForce RTX 4080 (12GB GDDR6)' },
      { id: 'sp-26', productId: 'prod-rog-zephyrus-g16', specGroup: 'Memory & Storage', specName: 'RAM', specValue: '32GB LPDDR5X 7467MHz' },
      { id: 'sp-27', productId: 'prod-rog-zephyrus-g16', specGroup: 'Memory & Storage', specName: 'Storage', specValue: '1TB M.2 NVMe PCIe 4.0 SSD' },
      { id: 'sp-28', productId: 'prod-rog-zephyrus-g16', specGroup: 'Battery & Power', specName: 'Battery Capacity', specValue: '90Wh (240W AC Adapter)' },
      { id: 'sp-29', productId: 'prod-rog-zephyrus-g16', specGroup: 'Design & Build', specName: 'Weight', specValue: '1.85 kg (4.07 lbs)' },
    ],
    createdAt: '2025-02-01T11:00:00Z',
    updatedAt: '2025-03-05T09:00:00Z',
  },
  {
    id: 'prod-iphone-16-pro-max',
    name: 'iPhone 16 Pro Max 512GB (Titanium Desert, A18 Pro)',
    sku: 'APP-IPH16PM-512',
    barcode: '195949019234',
    categoryId: 'cat-phones',
    brandId: 'brand-apple',
    description: 'Grade 5 Titanium design with thinner borders, 6.9-inch Super Retina XDR display, Camera Control capacitive button, 48MP Fusion camera with 5x optical telephoto, and A18 Pro chip.',
    basePrice: 1399.00,
    salePrice: 1349.00,
    stockQuantity: 24,
    rating: 4.9,
    reviewCount: 88,
    isFeatured: true,
    images: [
      { id: 'img-iph-1', productId: 'prod-iphone-16-pro-max', imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'iPhone 16 Pro Max Titanium' },
      { id: 'img-iph-2', productId: 'prod-iphone-16-pro-max', imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80', isPrimary: false, altText: 'Triple lens camera system' },
    ],
    specifications: [
      { id: 'sp-30', productId: 'prod-iphone-16-pro-max', specGroup: 'Display', specName: 'Screen Size', specValue: '6.9-inch' },
      { id: 'sp-31', productId: 'prod-iphone-16-pro-max', specGroup: 'Display', specName: 'Resolution', specValue: '2868 x 1320 (460 ppi, 2000 nits peak)' },
      { id: 'sp-32', productId: 'prod-iphone-16-pro-max', specGroup: 'Display', specName: 'Refresh Rate', specValue: '120Hz ProMotion Always-On' },
      { id: 'sp-33', productId: 'prod-iphone-16-pro-max', specGroup: 'Performance', specName: 'Processor', specValue: 'Apple A18 Pro (6-core CPU, 6-core GPU, 16-core NPU)' },
      { id: 'sp-34', productId: 'prod-iphone-16-pro-max', specGroup: 'Memory & Storage', specName: 'RAM', specValue: '8GB' },
      { id: 'sp-35', productId: 'prod-iphone-16-pro-max', specGroup: 'Memory & Storage', specName: 'Storage', specValue: '512GB NVMe' },
      { id: 'sp-36', productId: 'prod-iphone-16-pro-max', specGroup: 'Camera', specName: 'Rear Cameras', specValue: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Telephoto' },
      { id: 'sp-37', productId: 'prod-iphone-16-pro-max', specGroup: 'Battery & Power', specName: 'Battery Capacity', specValue: '4685mAh (Up to 33 hrs video)' },
      { id: 'sp-38', productId: 'prod-iphone-16-pro-max', specGroup: 'Connectivity', specName: '5G / Wi-Fi', specValue: '5G Sub-6/mmWave, Wi-Fi 7 (802.11be), USB-C 3.0' },
    ],
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-03-01T12:00:00Z',
  },
  {
    id: 'prod-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra (512GB, Titanium Gray, Galaxy AI)',
    sku: 'SAM-S24U-512G',
    barcode: '887276801923',
    categoryId: 'cat-phones',
    brandId: 'brand-samsung',
    description: 'Titanium armor with flat 6.8" Dynamic AMOLED 2X 1-120Hz anti-reflective Corning Gorilla Armor glass. Built-in S Pen, 200MP quad telephoto zoom, and Snapdragon 8 Gen 3 for Galaxy.',
    basePrice: 1419.00,
    salePrice: 1249.00,
    stockQuantity: 15,
    rating: 4.8,
    reviewCount: 64,
    isFeatured: true,
    isDeal: true,
    images: [
      { id: 'img-s24u-1', productId: 'prod-galaxy-s24-ultra', imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Galaxy S24 Ultra with S Pen' },
    ],
    specifications: [
      { id: 'sp-39', productId: 'prod-galaxy-s24-ultra', specGroup: 'Display', specName: 'Screen Size', specValue: '6.8-inch' },
      { id: 'sp-40', productId: 'prod-galaxy-s24-ultra', specGroup: 'Display', specName: 'Resolution', specValue: '3120 x 1440 (QHD+ Dynamic AMOLED 2X, 2600 nits)' },
      { id: 'sp-41', productId: 'prod-galaxy-s24-ultra', specGroup: 'Display', specName: 'Refresh Rate', specValue: '1-120Hz Adaptive LTPO' },
      { id: 'sp-42', productId: 'prod-galaxy-s24-ultra', specGroup: 'Performance', specName: 'Processor', specValue: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy' },
      { id: 'sp-43', productId: 'prod-galaxy-s24-ultra', specGroup: 'Memory & Storage', specName: 'RAM', specValue: '12GB LPDDR5X' },
      { id: 'sp-44', productId: 'prod-galaxy-s24-ultra', specGroup: 'Memory & Storage', specName: 'Storage', specValue: '512GB UFS 4.0' },
      { id: 'sp-45', productId: 'prod-galaxy-s24-ultra', specGroup: 'Camera', specName: 'Rear Cameras', specValue: '200MP Wide + 50MP 5x Periscope + 10MP 3x + 12MP Ultra-wide' },
      { id: 'sp-46', productId: 'prod-galaxy-s24-ultra', specGroup: 'Battery & Power', specName: 'Battery Capacity', specValue: '5000mAh (45W Super Fast Charging 2.0)' },
      { id: 'sp-47', productId: 'prod-galaxy-s24-ultra', specGroup: 'Connectivity', specName: '5G / Wi-Fi', specValue: '5G, Wi-Fi 7, Bluetooth 5.3, UWB' },
    ],
    createdAt: '2025-01-12T10:00:00Z',
    updatedAt: '2025-03-03T11:00:00Z',
  },
  {
    id: 'prod-sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
    sku: 'SNY-WH1000XM5-BLK',
    barcode: '027242923989',
    categoryId: 'cat-audio',
    brandId: 'brand-sony',
    description: 'Industry-leading noise cancellation with two processors and 8 microphones. Hi-Res Audio wireless with LDAC, Auto NC Optimizer, 30-hour battery life with 3-minute quick charge for 3 hours playback.',
    basePrice: 399.99,
    salePrice: 348.00,
    stockQuantity: 32,
    rating: 4.8,
    reviewCount: 95,
    isFeatured: true,
    isDeal: true,
    images: [
      { id: 'img-xm5-1', productId: 'prod-sony-wh1000xm5', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Sony WH-1000XM5 Black' },
      { id: 'img-xm5-2', productId: 'prod-sony-wh1000xm5', imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80', isPrimary: false, altText: 'Headband and earcups' },
    ],
    specifications: [
      { id: 'sp-48', productId: 'prod-sony-wh1000xm5', specGroup: 'Performance', specName: 'Driver Size', specValue: '30mm Carbon Fiber composite dome' },
      { id: 'sp-49', productId: 'prod-sony-wh1000xm5', specGroup: 'Performance', specName: 'Frequency Response', specValue: '4Hz - 40,000Hz (Hi-Res Audio)' },
      { id: 'sp-50', productId: 'prod-sony-wh1000xm5', specGroup: 'Performance', specName: 'Noise Cancellation', specValue: 'HD Noise Cancelling Processor QN1 + V1' },
      { id: 'sp-51', productId: 'prod-sony-wh1000xm5', specGroup: 'Battery & Power', specName: 'Battery Life', specValue: '30 hours (ANC On) / 40 hours (ANC Off)' },
      { id: 'sp-52', productId: 'prod-sony-wh1000xm5', specGroup: 'Connectivity', specName: 'Bluetooth Codecs', specValue: 'Bluetooth 5.2 (LDAC, AAC, SBC, Multipoint 2 devices)' },
      { id: 'sp-53', productId: 'prod-sony-wh1000xm5', specGroup: 'Design & Build', specName: 'Weight', specValue: '250g (Ultra-lightweight soft fit leather)' },
    ],
    createdAt: '2025-01-08T09:00:00Z',
    updatedAt: '2025-02-28T14:00:00Z',
  },
  {
    id: 'prod-bose-qc-ultra',
    name: 'Bose QuietComfort Ultra Wireless Noise-Canceling Headphones',
    sku: 'BOS-QCU-SMK',
    barcode: '017817842911',
    categoryId: 'cat-audio',
    brandId: 'brand-bose',
    description: 'Groundbreaking Bose Immersive Audio spatial sound, world-class active noise cancellation with CustomTune technology, luxurious comfort, and up to 24 hours of playback.',
    basePrice: 429.00,
    salePrice: 379.00,
    stockQuantity: 21,
    rating: 4.7,
    reviewCount: 53,
    isFeatured: false,
    images: [
      { id: 'img-bose-1', productId: 'prod-bose-qc-ultra', imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Bose QC Ultra Smoke White' },
    ],
    specifications: [
      { id: 'sp-54', productId: 'prod-bose-qc-ultra', specGroup: 'Performance', specName: 'Sound Engine', specValue: 'Bose Immersive Spatial Audio + CustomTune' },
      { id: 'sp-55', productId: 'prod-bose-qc-ultra', specGroup: 'Battery & Power', specName: 'Battery Life', specValue: 'Up to 24 hours (18 hours with Immersive Audio)' },
      { id: 'sp-56', productId: 'prod-bose-qc-ultra', specGroup: 'Connectivity', specName: 'Bluetooth', specValue: 'Bluetooth 5.3 with Snapdragon Sound / aptX Adaptive' },
      { id: 'sp-57', productId: 'prod-bose-qc-ultra', specGroup: 'Design & Build', specName: 'Weight', specValue: '252g' },
    ],
    createdAt: '2025-01-15T11:00:00Z',
    updatedAt: '2025-03-01T16:00:00Z',
  },
  {
    id: 'prod-samsung-odyssey-oled-g9',
    name: 'Samsung Odyssey OLED G9 49" Curved Dual QHD 240Hz 0.03ms',
    sku: 'SAM-G95SC-49',
    barcode: '887276774129',
    categoryId: 'cat-displays',
    brandId: 'brand-samsung',
    description: 'The definitive 49-inch 32:9 curved gaming monitor. Featuring a Neo Quantum Processor Pro OLED panel with 0.03ms response time, 240Hz refresh rate, DisplayHDR True Black 400, and built-in Gaming Hub.',
    basePrice: 1799.99,
    salePrice: 1399.99,
    stockQuantity: 6,
    rating: 4.9,
    reviewCount: 38,
    isFeatured: true,
    isDeal: true,
    images: [
      { id: 'img-g9-1', productId: 'prod-samsung-odyssey-oled-g9', imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Samsung Odyssey OLED G9 Curved' },
    ],
    specifications: [
      { id: 'sp-58', productId: 'prod-samsung-odyssey-oled-g9', specGroup: 'Display', specName: 'Screen Size', specValue: '49-inch Dual QHD (32:9 Super UltraWide)' },
      { id: 'sp-59', productId: 'prod-samsung-odyssey-oled-g9', specGroup: 'Display', specName: 'Resolution', specValue: '5120 x 1440 (OLED Curved 1800R)' },
      { id: 'sp-60', productId: 'prod-samsung-odyssey-oled-g9', specGroup: 'Display', specName: 'Refresh Rate', specValue: '240Hz / 0.03ms (GtG)' },
      { id: 'sp-61', productId: 'prod-samsung-odyssey-oled-g9', specGroup: 'Display', specName: 'HDR & Brightness', specValue: 'DisplayHDR True Black 400 (Peak 1000 nits)' },
      { id: 'sp-62', productId: 'prod-samsung-odyssey-oled-g9', specGroup: 'Connectivity', specName: 'Video Inputs', specValue: 'HDMI 2.1, Micro HDMI 2.1, DisplayPort 1.4, USB Hub' },
    ],
    createdAt: '2025-01-02T10:00:00Z',
    updatedAt: '2025-03-06T10:00:00Z',
  },
  {
    id: 'prod-dell-ultrasharp-32-4k',
    name: 'Dell UltraSharp 32 4K USB-C Hub Monitor (IPS Black, 98% DCI-P3)',
    sku: 'DEL-U3224KB-4K',
    barcode: '884116410294',
    categoryId: 'cat-displays',
    brandId: 'brand-dell',
    description: 'Premier 31.5-inch 4K IPS Black monitor with 2000:1 contrast ratio, 90W USB-C power delivery, RJ45 Ethernet pass-through, and factory color calibrated Delta E < 2.',
    basePrice: 899.99,
    salePrice: 799.99,
    stockQuantity: 14,
    rating: 4.8,
    reviewCount: 22,
    isFeatured: false,
    images: [
      { id: 'img-u32-1', productId: 'prod-dell-ultrasharp-32-4k', imageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Dell UltraSharp 32 inch 4K Monitor' },
    ],
    specifications: [
      { id: 'sp-63', productId: 'prod-dell-ultrasharp-32-4k', specGroup: 'Display', specName: 'Screen Size', specValue: '31.5-inch' },
      { id: 'sp-64', productId: 'prod-dell-ultrasharp-32-4k', specGroup: 'Display', specName: 'Resolution', specValue: '3840 x 2160 (4K UHD IPS Black)' },
      { id: 'sp-65', productId: 'prod-dell-ultrasharp-32-4k', specGroup: 'Display', specName: 'Color Gamut', specValue: '98% DCI-P3, 100% sRGB, 2000:1 Contrast' },
      { id: 'sp-66', productId: 'prod-dell-ultrasharp-32-4k', specGroup: 'Connectivity', specName: 'Hub Ports', specValue: 'Thunderbolt 4 (90W PD), DP 1.4, HDMI 2.1, RJ45 2.5GbE' },
    ],
    createdAt: '2025-01-18T14:00:00Z',
    updatedAt: '2025-02-20T10:00:00Z',
  },
  {
    id: 'prod-nvidia-rtx-4090',
    name: 'NVIDIA GeForce RTX 4090 Founders Edition 24GB GDDR6X',
    sku: 'NVD-RTX4090-FE24',
    barcode: '812674026885',
    categoryId: 'cat-gaming',
    brandId: 'brand-nvidia',
    description: 'The ultimate GeForce GPU. Powered by the NVIDIA Ada Lovelace architecture, 16384 CUDA cores, 24GB of ultra-fast GDDR6X VRAM, DLSS 3 Frame Generation, and 3rd-generation RT cores.',
    basePrice: 1799.00,
    stockQuantity: 4,
    rating: 4.9,
    reviewCount: 49,
    isFeatured: true,
    images: [
      { id: 'img-rtx-1', productId: 'prod-nvidia-rtx-4090', imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'NVIDIA RTX 4090 Founders Edition' },
    ],
    specifications: [
      { id: 'sp-67', productId: 'prod-nvidia-rtx-4090', specGroup: 'Performance', specName: 'CUDA Cores', specValue: '16,384' },
      { id: 'sp-68', productId: 'prod-nvidia-rtx-4090', specGroup: 'Performance', specName: 'Boost Clock', specValue: '2.52 GHz' },
      { id: 'sp-69', productId: 'prod-nvidia-rtx-4090', specGroup: 'Memory & Storage', specName: 'VRAM', specValue: '24 GB GDDR6X (384-bit)' },
      { id: 'sp-70', productId: 'prod-nvidia-rtx-4090', specGroup: 'Battery & Power', specName: 'Power Consumption (TDP)', specValue: '450W (850W PSU Recommended)' },
      { id: 'sp-71', productId: 'prod-nvidia-rtx-4090', specGroup: 'Design & Build', specName: 'Dimensions', specValue: '304 mm x 137 mm (3-slot)' },
    ],
    createdAt: '2025-01-04T12:00:00Z',
    updatedAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'prod-logitech-g502-x-plus',
    name: 'Logitech G502 X PLUS LIGHTSPEED Wireless RGB Gaming Mouse',
    sku: 'LOG-G502X-PLUS',
    barcode: '097855171923',
    categoryId: 'cat-gaming',
    brandId: 'brand-logitech',
    description: 'The world’s most popular gaming mouse redesigned. LIGHTFORCE hybrid optical-mechanical switches, HERO 25K sub-micron sensor, 8-zone active LIGHTSYNC RGB, and POWERPLAY wireless charging compatibility.',
    basePrice: 159.99,
    salePrice: 139.99,
    stockQuantity: 40,
    rating: 4.8,
    reviewCount: 78,
    isFeatured: false,
    isDeal: true,
    images: [
      { id: 'img-g502-1', productId: 'prod-logitech-g502-x-plus', imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Logitech G502 X Plus Wireless Gaming Mouse' },
    ],
    specifications: [
      { id: 'sp-72', productId: 'prod-logitech-g502-x-plus', specGroup: 'Performance', specName: 'Sensor', specValue: 'HERO 25K (100 - 25,600 DPI, 400 IPS)' },
      { id: 'sp-73', productId: 'prod-logitech-g502-x-plus', specGroup: 'Performance', specName: 'Switches', specValue: 'LIGHTFORCE Hybrid Optical-Mechanical' },
      { id: 'sp-74', productId: 'prod-logitech-g502-x-plus', specGroup: 'Battery & Power', specName: 'Battery Life', specValue: '120 hours continuous (37 hours RGB on)' },
      { id: 'sp-75', productId: 'prod-logitech-g502-x-plus', specGroup: 'Design & Build', specName: 'Weight', specValue: '106 grams (PTFE glide feet)' },
    ],
    createdAt: '2025-01-14T09:00:00Z',
    updatedAt: '2025-02-25T11:00:00Z',
  },
  {
    id: 'prod-apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2 (Titanium Case, GPS + Cellular 49mm)',
    sku: 'APP-AWU2-49TI',
    barcode: '195949129038',
    categoryId: 'cat-smarthome',
    brandId: 'brand-apple',
    description: 'The most rugged and capable Apple Watch. Powered by the S9 SiP with Double Tap gesture, 3000 nits brightest display, precision dual-frequency GPS, depth gauge to 40m, and up to 72 hours in Low Power Mode.',
    basePrice: 799.00,
    salePrice: 749.00,
    stockQuantity: 19,
    rating: 4.9,
    reviewCount: 31,
    isFeatured: true,
    isDeal: true,
    images: [
      { id: 'img-awu-1', productId: 'prod-apple-watch-ultra-2', imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80', isPrimary: true, altText: 'Apple Watch Ultra 2 on wrist' },
    ],
    specifications: [
      { id: 'sp-76', productId: 'prod-apple-watch-ultra-2', specGroup: 'Display', specName: 'Screen Size & Brightness', specValue: '49mm Sapphire Crystal (3000 nits Always-On OLED)' },
      { id: 'sp-77', productId: 'prod-apple-watch-ultra-2', specGroup: 'Performance', specName: 'Chipset', specValue: 'Apple S9 SiP with 64-bit dual-core processor' },
      { id: 'sp-78', productId: 'prod-apple-watch-ultra-2', specGroup: 'Battery & Power', specName: 'Battery Life', specValue: '36 hours normal / 72 hours Low Power Mode' },
      { id: 'sp-79', productId: 'prod-apple-watch-ultra-2', specGroup: 'Design & Build', specName: 'Water Resistance', specValue: '100m water resistant, EN13319 dive certified to 40m' },
    ],
    createdAt: '2025-01-22T10:00:00Z',
    updatedAt: '2025-03-04T12:00:00Z',
  },
];

export const initialPriceHistories: Record<string, PriceHistoryPoint[]> = {
  'prod-macbook-pro-16': [
    { id: 'ph-1', productId: 'prod-macbook-pro-16', price: 3599.00, changedAt: '2024-10-01T00:00:00Z', note: 'Product launch price' },
    { id: 'ph-2', productId: 'prod-macbook-pro-16', price: 3499.00, changedAt: '2024-11-20T00:00:00Z', note: 'Black Friday promotion' },
    { id: 'ph-3', productId: 'prod-macbook-pro-16', price: 3499.00, changedAt: '2025-01-05T00:00:00Z', note: 'Standard base price' },
    { id: 'ph-4', productId: 'prod-macbook-pro-16', price: 3349.00, changedAt: '2025-02-15T00:00:00Z', note: 'Valentine Spring discount' },
    { id: 'ph-5', productId: 'prod-macbook-pro-16', price: 3299.00, changedAt: '2025-03-01T00:00:00Z', note: 'Current promo deal' },
  ],
  'prod-iphone-16-pro-max': [
    { id: 'ph-6', productId: 'prod-iphone-16-pro-max', price: 1399.00, changedAt: '2024-09-20T00:00:00Z', note: 'Launch MSRP' },
    { id: 'ph-7', productId: 'prod-iphone-16-pro-max', price: 1399.00, changedAt: '2024-12-01T00:00:00Z', note: 'Holiday regular' },
    { id: 'ph-8', productId: 'prod-iphone-16-pro-max', price: 1349.00, changedAt: '2025-02-10T00:00:00Z', note: 'Trade-in rebate bonus' },
  ],
  'prod-sony-wh1000xm5': [
    { id: 'ph-9', productId: 'prod-sony-wh1000xm5', price: 399.99, changedAt: '2024-09-01T00:00:00Z', note: 'Retail price' },
    { id: 'ph-10', productId: 'prod-sony-wh1000xm5', price: 369.00, changedAt: '2024-11-25T00:00:00Z', note: 'Cyber Week discount' },
    { id: 'ph-11', productId: 'prod-sony-wh1000xm5', price: 398.00, changedAt: '2025-01-02T00:00:00Z', note: 'Price reset' },
    { id: 'ph-12', productId: 'prod-sony-wh1000xm5', price: 348.00, changedAt: '2025-02-28T00:00:00Z', note: 'Limited-time bundle deal' },
  ],
  'prod-samsung-odyssey-oled-g9': [
    { id: 'ph-13', productId: 'prod-samsung-odyssey-oled-g9', price: 1799.99, changedAt: '2024-08-15T00:00:00Z', note: 'Original MSRP' },
    { id: 'ph-14', productId: 'prod-samsung-odyssey-oled-g9', price: 1599.00, changedAt: '2024-11-15T00:00:00Z', note: 'Holiday sale' },
    { id: 'ph-15', productId: 'prod-samsung-odyssey-oled-g9', price: 1499.00, changedAt: '2025-01-10T00:00:00Z', note: 'New year promotion' },
    { id: 'ph-16', productId: 'prod-samsung-odyssey-oled-g9', price: 1399.99, changedAt: '2025-03-01T00:00:00Z', note: 'All-time lowest price' },
  ],
};

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-macbook-pro-16',
    userId: 'usr-customer-1',
    userName: 'David Chen',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'The ultimate software developer workstation',
    comment: 'The M3 Max compiles large C++ and Rust codebases in seconds without the fans ever spinning above whisper level. The 16.2" Liquid Retina XDR screen is razor-sharp for dual-window IDE splits. Outstanding machine.',
    verifiedPurchase: true,
    helpfulCount: 28,
    status: 'APPROVED',
    createdAt: '2025-02-14T18:22:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-macbook-pro-16',
    userId: 'usr-sarah-m',
    userName: 'Sarah Miller',
    rating: 5,
    title: 'Battery life feels like science fiction',
    comment: 'I worked through an 11-hour transatlantic flight with Figma, 4K video playback, and Docker running, and still landed with 38% battery. Space Black finish genuinely minimizes fingerprints compared to Midnight.',
    verifiedPurchase: true,
    helpfulCount: 19,
    status: 'APPROVED',
    createdAt: '2025-02-20T11:45:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-sony-wh1000xm5',
    userId: 'usr-customer-1',
    userName: 'David Chen',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Cancels loud subway screeching completely',
    comment: 'The 8-mic array with Auto NC Optimizer is visibly superior to the XM4. Bluetooth multipoint seamlessly switches between my MacBook and phone during Zoom calls.',
    verifiedPurchase: true,
    helpfulCount: 14,
    status: 'APPROVED',
    createdAt: '2025-02-18T09:12:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-samsung-odyssey-oled-g9',
    userId: 'usr-marcus-k',
    userName: 'Marcus Koenig',
    rating: 5,
    title: 'Pure gaming transcendence',
    comment: 'Playing Cyberpunk 2077 and Microsoft Flight Simulator across a 49-inch 240Hz 32:9 OLED canvas is jaw-dropping. Perfect inky blacks and zero ghosting thanks to 0.03ms response.',
    verifiedPurchase: true,
    helpfulCount: 22,
    status: 'APPROVED',
    createdAt: '2025-02-26T20:04:00Z',
  },
];

export const initialFAQs: FAQ[] = [
  {
    id: 'faq-1',
    productId: 'prod-macbook-pro-16',
    question: 'How many external monitors can the M3 Max MacBook Pro support simultaneously?',
    answer: 'The M3 Max supports up to four external displays simultaneously: up to three 6K displays at 60Hz over Thunderbolt and one 4K display at 144Hz over HDMI 2.1.',
  },
  {
    id: 'faq-2',
    productId: 'prod-macbook-pro-16',
    question: 'Does this model include the 140W USB-C Power Adapter and MagSafe 3 cable in the box?',
    answer: 'Yes! It includes the official Apple 140W USB-C Power Adapter and a 2-meter color-matched Space Black braided USB-C to MagSafe 3 cable.',
  },
  {
    id: 'faq-3',
    productId: 'prod-sony-wh1000xm5',
    question: 'Can I use these wired when the battery is completely drained?',
    answer: 'Yes, the WH-1000XM5 includes a 3.5mm audio cable and can function as a passive wired headphone even if the internal battery is at 0%.',
  },
  {
    id: 'faq-4',
    productId: 'prod-samsung-odyssey-oled-g9',
    question: 'Does this monitor support Picture-by-Picture (PBP) for two distinct PCs?',
    answer: 'Yes, Picture-by-Picture (PBP) and Picture-in-Picture (PIP) allow you to view two different video input sources side-by-side at 2560x1440 resolution each.',
  },
];

export const initialDocuments: ProductDocument[] = [
  {
    id: 'doc-1',
    productId: 'prod-macbook-pro-16',
    docType: 'MANUAL',
    title: 'MacBook Pro 16" User QuickStart & Hardware Guide (PDF)',
    fileUrl: '#download-manual-mbp16',
    fileSize: '4.2 MB',
  },
  {
    id: 'doc-2',
    productId: 'prod-macbook-pro-16',
    docType: 'WARRANTY',
    title: 'Apple Limited 1-Year Global Hardware Warranty Certificate (PDF)',
    fileUrl: '#download-warranty-apple',
    fileSize: '1.1 MB',
  },
  {
    id: 'doc-3',
    productId: 'prod-sony-wh1000xm5',
    docType: 'MANUAL',
    title: 'Sony WH-1000XM5 Reference Guide & Companion App Setup (PDF)',
    fileUrl: '#download-manual-xm5',
    fileSize: '2.8 MB',
  },
  {
    id: 'doc-4',
    productId: 'prod-samsung-odyssey-oled-g9',
    docType: 'SPEC_SHEET',
    title: 'Samsung Odyssey OLED G9 Technical Spec Sheet & VESA Mount Guide (PDF)',
    fileUrl: '#download-specs-g9',
    fileSize: '3.5 MB',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'VM-2025-98104',
    userId: 'usr-customer-1',
    userName: 'David Chen',
    userEmail: 'david.chen@example.com',
    items: [
      {
        id: 'oi-1',
        productId: 'prod-sony-wh1000xm5',
        productName: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
        productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        sku: 'SNY-WH1000XM5-BLK',
        unitPrice: 348.00,
        quantity: 1,
        totalPrice: 348.00,
      },
    ],
    subtotal: 348.00,
    discount: 0,
    tax: 27.84,
    shippingCost: 0,
    totalAmount: 375.84,
    status: 'DELIVERED',
    shippingAddress: {
      fullName: 'David Chen',
      street: '742 Evergreen Terrace, Apt 4B',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94107',
      country: 'United States',
      phone: '+1 (415) 555-0192',
    },
    paymentMethod: {
      type: 'CREDIT_CARD',
      last4: '4242',
      cardBrand: 'Visa',
    },
    trackingNumber: '1Z9999999999999999',
    timeline: [
      { status: 'PENDING', timestamp: '2025-02-16T09:15:00Z', description: 'Order placed & payment authorized.' },
      { status: 'CONFIRMED', timestamp: '2025-02-16T09:30:00Z', description: 'Order verified by VoltMart logistics.' },
      { status: 'SHIPPED', timestamp: '2025-02-16T14:20:00Z', description: 'Handed off to carrier in San Jose Hub.' },
      { status: 'DELIVERED', timestamp: '2025-02-18T11:40:00Z', description: 'Package delivered to front desk / mailbox.' },
    ],
    createdAt: '2025-02-16T09:15:00Z',
  },
];
